app/__init__.py
app/common/api.py
app/common/database.py
app/common/objects.py
app/routes/web/replays.py
app/routes/web/scoring.py

- The 'plays' table now gets updated once a score submission request was made
- A backup url for .osu files was added (https://old.ppy.sh/osu/<beatmap_id>)
- The 'StarletteHTTPException' now has a custom exception handler
- Performance and accuracy always get updated on score submission request
- Update 'replay_views' when requesting replay

Update database 'plays' table on score submission & other improvements

---

.env_example
app/objects.py
app/routes/web/scoring.py
app/routes/web/screenshots.py
app/services/anticheat/circleguard.py
app/services/performance/__init__.py
app/services/performance/ppv2_akatsuki.py
config.py
requirements.txt

- Add *akatsuki pp* system, which can be enabled inside the env file
- Fix request type in */web/osu-ss.php*
- Change ban reason for bad flags
- Change anticheat report message
- Add todo for anticheat (score comparison)

Add akatsuki pp system (optional) & fix /osu-ss.php endpoint

---

README.md
app/__init__.py
app/common/objects.py
app/highlights.py
app/routes/web/scoring.py

This will add banchobot messages on #highlight, when a player ranks up into the top 10, or when a player achieves a set rank on a beatmap. There are still things to do, such as achievement messages or pp record messages, which are gonna be implemented in the future.

Add #highlight messages

---

app/common/objects.py

Please read: https://github.com/Lekuruu/anchor/pull/8

Fix static datetime rows

---

.env_example
app/achievements.py
app/common/database.py
app/common/objects.py
app/common/storage.py
app/routes/__init__.py
app/routes/images.py
app/routes/web/scoring.py
app/services/anticheat/circleguard.py
utils.py

This will implement the old achievements, that were present back in the day. I've also updated the setup function, to create and migrate buckets automatically.
This still needs to be tested, but I think it's ready to merge into dev at least.

Implement achievements

---

app/routes/web/screenshots.py
utils.py

Add screenshot size and content validation

---

app/highlights.py

Fix highlight message when score is on not on leaderboards

---

app/common/database.py
app/constants.py
app/highlights.py
app/routes/web/direct.py
app/routes/web/scoring.py

- "Ranked" display mode, now includes Approved/Loved maps
- "Newest" query will now get filtered by id, instead of time
- "Played" display mode will now *only* include ranked & approved maps
- Full-text search was refactored and the "query_string" attribute is not needed anymore (TODO?)
- Beatmap highlights now include mods (e.g. HDHR)
- Implemented pp record highlights, as well as new top plays
- ```app.highlights.check(...)``` is now threaded

Refactor highlights and optimize osu! direct search queries

---

app/objects.py
app/routes/rating/rate2.py
app/routes/static.py
app/routes/web/comments.py
app/routes/web/leaderboards.py
app/routes/web/replays.py
app/routes/web/scoring.py

- Support for legacy comments (https://github.com/osuTitanic/deck/commit/a9671a2226cef1147ba06d555c494a1e9faf509d)
- Support for legacy replays (https://github.com/osuTitanic/deck/commit/04aa2c60627dd2a6db509431792de65644131483)
- Support for legacy score submission (https://github.com/osuTitanic/deck/commit/8a9c4ce091936e21a75b762b5ee9e20d5f14d6de) (https://github.com/osuTitanic/deck/commit/5ff6e1716d76044f5faccbdf54df58fab079e337) (https://github.com/osuTitanic/deck/commit/6ad83acda92325ed85a01090850c4f49a2262030)
- Support for `/osu-submit.php` (https://github.com/osuTitanic/deck/commit/5ff6e1716d76044f5faccbdf54df58fab079e337)
- Support for `/osu-getscores5.php` (https://github.com/osuTitanic/deck/commit/6677264b46f9389e097509f67c7c3c08ab83b395)

Implement more legacy client support (production)

---

app/objects.py
app/routes/static.py
app/routes/web/__init__.py
app/routes/web/leaderboards.py
app/routes/web/status.py
utils.py

This implements the following endpoints, which are used in older clients:
- /osu-getscores4.php
- /osu-getscores3.php
- /osu-getscores2.php
and some other bug fixes.

Add new endpoints for legacy clients (production)

---

app/routes/web/scoring.py

This will probably not scale pretty well, but should give more accuracy when it comes to these calculations.

Refactor pp, score & acc calculation to using all scores

---

app/routes/web/error.py
app/routes/web/screenshots.py
utils.py

- Removed `/osu-ss.php` endpoint, because of [this](https://www.reddit.com/r/osugame/comments/3vyi7h/how_osu_voilates_your_privacy/) (https://github.com/osuTitanic/deck/commit/df7cb4a26e1e10a02cbd5310f96526569fb67d0a)
- Implemented authentication for `/osu-error.php` (https://github.com/osuTitanic/deck/commit/c4209bcd253108eeafa2b36d3384815952dfce3c)
- Implemented `osu_error` event for bancho (https://github.com/osuTitanic/deck/commit/6d72807045a08ac80ad4524433e47af43e11a09c)

Refactor `/osu-error.php` endpoint & remove `/osu-ss.php` endpoint

---

app/__init__.py
app/achievements.py
app/highlights.py
app/objects.py
app/routes/static.py
app/routes/web/scoring.py
utils.py

- Removed achievements from setup (https://github.com/osuTitanic/deck/commit/e70b566cfd7f536e71c1110827f751c4696ced12)
- Fixed dancer achievement (https://github.com/osuTitanic/deck/commit/0f8a0ed5b75600dc978b054345be86ef24e304a6)
- Fixed "lost first place" activity when second place is same player (https://github.com/osuTitanic/deck/commit/9224875400c31fb26d5f7f7c354afd0e41954c12)
- Refactored score submission (https://github.com/osuTitanic/deck/commit/07988ae0920f4325010f6edb8a801db8f6fb41d6) (https://github.com/osuTitanic/deck/commit/e55a5184f5f689d4cfc7c025cb6a8c399be5fc38) (https://github.com/osuTitanic/deck/commit/3826958ac25b371427b15bfcdf89d80abfcc18c8) (https://github.com/osuTitanic/deck/commit/fc14042dee51bec984643f7960ece8dadaabbdb8)
- Improve achievement processing time …

Refactor score submission code

---

app/routes/web/scoring.py
config.py

- Fixed a bug regarding the mailgun configuration
- Implemented replay validation
- Changed score submission time calculations
Resolves: #190

Implement replay validation

---

.env_example
app/__init__.py
app/routes/web/scoring.py
config.py

- Added discord webhook logging (`officer.call`)
- Added user agent validation on score submission

Add webhook logging

---

app/routes/web/direct.py
app/routes/web/error.py
app/routes/web/leaderboards.py
app/routes/web/scoring.py
utils.py

- Added global pp cap
- Added experimental user pp cap
- Refactored score submission time calculations
- Added bancho multiaccounting lock
- Added flagged/forbidden skins
- Fixed legacy leaderboard queries
- Add "verified" user groups
Resolves: #196, https://github.com/osuTitanic/anchor/issues/210

Add user whitelist, add global pp cap & fix legacy leaderboard queries

---

app/objects.py
app/routes/web/connect.py
app/routes/web/scoring.py
utils.py

This should fix some basic issues with client versions past b20130712.
This includes:
- Score submission objects (https://github.com/osuTitanic/deck/commit/59df9f037f46f92f9ee42eb901b03d6816a6fb32)
- New `bancho_connect.php` endpoint (https://github.com/osuTitanic/deck/commit/7e0013c16952c5e0e66541d4bece5bb5e81b03a7)
and more.

Add some amount of support for client versions past 2013

---

app/routes/static.py
app/routes/web/connect.py
app/routes/web/direct.py
app/routes/web/leaderboards.py
app/routes/web/scoring.py
utils.py

- Fixed osu config parsing (https://github.com/osuTitanic/deck/commit/f062c7a03cc3f942c0e478b5c215a6581bc9e28e)
- Added bundled beatmap downloads (https://github.com/osuTitanic/deck/commit/b4f28289502044853967201ec358bcbabe9c2085)
- Fixed client hash mismatching in newer versions (https://github.com/osuTitanic/deck/commit/f055e7e940a48b65d353b13cc6a396aa1dc516c7)
- Fixed username in score string (https://github.com/osuTitanic/deck/commit/81daa4407ae6fbce0965b3a73b61d09bca236882)
- Implemented new leaderboard versions (https://github.com/osuTitanic/deck/commit/e46df2a8c0bce6c38b710a0248f291f499ff83c3)
- Implemented new osu!direct search versions (https://github.com/osuTitanic/deck/commit/0b7b267d71fa44b62e4178016e5a9cb08e3a439e)
- Added new client flags to score submission …

Implement new client endpoints

---

.github/dependabot.yml
app/routes/web/__init__.py
app/routes/web/scoring.py
app/routes/web/stats.py
app/routes/web/updates.py
config.py

I hope this will fix the annoying `osu-error.php` spams...

Implement `/web/check-updates.php` endpoint

---

.github/dependabot.yml
README.md
app/objects.py
app/routes/web/scoring.py
config.py

I've finally decided to implement this. Advertising this server to support all clients, without having score submission for some of them is pretty stupid.
To all the people with unverified client access on titanic, please behave.

Implement modern score submission

---

app/routes/rating/rate.py
app/routes/web/ratings.py

I've decided to create a database table that allows you to add beatmap mirrors. You can add mirrors for osz files, beatmap files, beatmap thumbnails and beatmap audio previews. You can also specify a server (osu.ppy.sh or local), although I still need to make api endpoints for them.

Implement resource mirror table for osu! direct

---

app/routes/web/__init__.py
app/routes/web/benchmark.py

the riskiest one yet
Closes #286

Add benchmark routing

---

app/routes/web/benchmark.py

Add client version to benchmark submission request

---

app/routes/web/beatmaps.py
config.py

-  Fix incorrect parsing of `VideoHash` causing issues with video upload
-  Fix video data length parsing
-  Fix parsing of genre & language IDs

1.6.1: Post-BSS update fixes

---

app/routes/web/beatmaps.py
utils.py

This system was a bit more complicated than I initially expected, but luckily there is a project out there, that gave me some good inspiration for the implementation. Huge thanks to [waffle-osu](https://github.com/Waffle-osu/Waffle/)!
See #308

Implement initial legacy beatmap submission endpoints

---

app/routes/web/benchmark.py

- Related to keel PR: https://github.com/osuTitanic/keel/pull/16
This adds the appropriate length checks as proposed in the above PR.

Verify length of benchmark renderer
